name: projet_info_06_2022
channels:
  - conda-forge
dependencies:
  - python=3.9
  - setuptools
  - black
  - numpy
  - matplotlib
  - pillow
  - jupyter
  - nbconvert
  - jupytext
  - BeautifulSoup4
  - requests
  - time
  - pandas