name: projet_info_06_2022
channels:
  - conda-forge
dependencies:
  - python=3.9
  - setuptools
  - numpy
  - matplotlib
  - jupyter
  - jupytext
  - BeautifulSoup4
  - requests
  - time
  - pandas
  - openpyxl
  - statsmodels